<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '您确定要删除此项目吗？',
    'Catalogs' => '目录',
    'Create Catalog' => '创建目录',
    'Delete' => '删除',
    'Delete failure' => '删除失败',
    'Please Select' => '请选择',
    'Save' => '保存',
    'The catalog is not empty, everything in it will be deleted, sure?' => '目录非空，其中的所有东西都会被删除，确定吗？',
    'Top Level' => '顶级',
    'Update' => '更新',
    'Update Catalog: ' => '更新目录：',
];
