<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cover' => '封面',
    'ID' => 'ID',
    'Location' => '定位',
    'Name' => '名称',
    'Path' => '路径',
    'Position' => '位置',
    'Sort' => '排序',
    'Type' => '类型',
    'after' => '之后',
    'before' => '之前',
    'category' => '分类',
    'page' => '页面',
];
